server:
  port: 8083

spring:
  application:
    name: playback-service
  cloud:
    config:
      uri: http://localhost:8888
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"