server:
  port: 8084

spring:
  application:
    name: recommendation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/recommendationdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"