server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sai459256/Cinemix#
          default-label: main
          clone-on-start: true
management:
  endpoints:
    web:
      exposure:
        include: "*"